// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 dotandev
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


// Copyright 2026 Erst Users

package bindings

import (
	"fmt"
	"strings"

	"github.com/dotandev/hintents/internal/abi"
	"github.com/dotandev/hintents/internal/endpoints"
	"github.com/stellar/go-stellar-sdk/xdr"
)

// GeneratorConfig holds configuration for TypeScript bindings generation
type GeneratorConfig struct {
	WasmBytes   []byte
	OutputDir   string
	PackageName string
	ContractID  string
	Network     string
}

// GeneratedFile represents a generated TypeScript file
type GeneratedFile struct {
	Path    string
	Content string
}

// Generator generates TypeScript bindings from Soroban contract specs
type Generator struct {
	config GeneratorConfig
	spec   *abi.ContractSpec
}

// NewGenerator creates a new bindings generator
func NewGenerator(config GeneratorConfig) *Generator {
	return &Generator{
		config: config,
	}
}

// Generate extracts the contract spec and generates TypeScript bindings
func (g *Generator) Generate() ([]GeneratedFile, error) {
	// Extract contract spec from WASM
	specBytes, err := abi.ExtractCustomSection(g.config.WasmBytes, "contractspecv0")
	if err != nil {
		return nil, fmt.Errorf("failed to extract contract spec: %w", err)
	}
	if specBytes == nil {
		return nil, fmt.Errorf("contract spec not found in WASM file")
	}

	// Decode contract spec
	g.spec, err = abi.DecodeContractSpec(specBytes)
	if err != nil {
		return nil, fmt.Errorf("failed to decode contract spec: %w", err)
	}

	// Generate files
	files := []GeneratedFile{
		{
			Path:    "types.ts",
			Content: g.generateTypes(),
		},
		{
			Path:    "client.ts",
			Content: g.generateClient(),
		},
		{
			Path:    "erst-integration.ts",
			Content: g.generateErstIntegration(),
		},
		{
			Path:    "index.ts",
			Content: g.generateIndex(),
		},
		{
			Path:    "package.json",
			Content: g.generatePackageJSON(),
		},
		{
			Path:    "README.md",
			Content: g.generateReadme(),
		},
	}

	return files, nil
}

// generateTypes generates TypeScript type definitions
func (g *Generator) generateTypes() string {
	var b strings.Builder

	b.WriteString("// Auto-generated TypeScript types for Soroban contract
")
	b.WriteString("// DO NOT EDIT - Generated by erst generate-bindings

")

	// Generate base types
	b.WriteString("export type Address = string;
")
	b.WriteString("export type Bytes = Uint8Array;
")
	b.WriteString("export type Symbol = string;

")

	// Generate struct types
	if len(g.spec.Structs) > 0 {
		b.WriteString("// Struct Types
")
		for _, s := range g.spec.Structs {
			g.generateStructType(&b, s)
		}
		b.WriteString("
")
	}

	// Generate enum types
	if len(g.spec.Enums) > 0 {
		b.WriteString("// Enum Types
")
		for _, e := range g.spec.Enums {
			g.generateEnumType(&b, e)
		}
		b.WriteString("
")
	}

	// Generate union types
	if len(g.spec.Unions) > 0 {
		b.WriteString("// Union Types
")
		for _, u := range g.spec.Unions {
			g.generateUnionType(&b, u)
		}
		b.WriteString("
")
	}

	// Generate error enum types
	if len(g.spec.ErrorEnums) > 0 {
		b.WriteString("// Error Types
")
		for _, e := range g.spec.ErrorEnums {
			g.generateErrorEnumType(&b, e)
		}
		b.WriteString("
")
	}

	// Generate event types
	if len(g.spec.Events) > 0 {
		b.WriteString("// Event Types
")
		for _, ev := range g.spec.Events {
			g.generateEventType(&b, ev)
		}
	}

	return b.String()
}

func (g *Generator) generateStructType(b *strings.Builder, s xdr.ScSpecUdtStructV0) {
	structName := string(s.Name)

	if s.Doc != "" {
		fmt.Fprintf(b, "/** %s */
", s.Doc)
	}

	fmt.Fprintf(b, "export interface %s {
", structName)
	for _, field := range s.Fields {
		tsType := g.mapTypeDefToTS(field.Type)
		fmt.Fprintf(b, "  %s: %s;
", field.Name, tsType)
	}
	b.WriteString("}

")
}

func (g *Generator) generateEnumType(b *strings.Builder, e xdr.ScSpecUdtEnumV0) {
	enumName := string(e.Name)

	if e.Doc != "" {
		fmt.Fprintf(b, "/** %s */
", e.Doc)
	}

	fmt.Fprintf(b, "export enum %s {
", enumName)
	for _, c := range e.Cases {
		fmt.Fprintf(b, "  %s = %d,
", c.Name, c.Value)
	}
	b.WriteString("}

")
}

func (g *Generator) generateUnionType(b *strings.Builder, u xdr.ScSpecUdtUnionV0) {
	unionName := string(u.Name)

	if u.Doc != "" {
		fmt.Fprintf(b, "/** %s */
", u.Doc)
	}

	// Generate discriminated union
	fmt.Fprintf(b, "export type %s = 
", unionName)

	for i, c := range u.Cases {
		switch c.Kind {
		case xdr.ScSpecUdtUnionCaseV0KindScSpecUdtUnionCaseVoidV0:
			fmt.Fprintf(b, "  | { tag: '%s' }", c.VoidCase.Name)
		case xdr.ScSpecUdtUnionCaseV0KindScSpecUdtUnionCaseTupleV0:
			types := make([]string, len(c.TupleCase.Type))
			for j, t := range c.TupleCase.Type {
				types[j] = g.mapTypeDefToTS(t)
			}
			fmt.Fprintf(b, "  | { tag: '%s'; values: [%s] }",
				c.TupleCase.Name, strings.Join(types, ", "))
		}

		if i < len(u.Cases)-1 {
			b.WriteString("
")
		}
	}
	b.WriteString(";

")
}

func (g *Generator) generateErrorEnumType(b *strings.Builder, e xdr.ScSpecUdtErrorEnumV0) {
	enumName := string(e.Name)

	if e.Doc != "" {
		fmt.Fprintf(b, "/** %s */
", e.Doc)
	}

	fmt.Fprintf(b, "export enum %s {
", enumName)
	for _, c := range e.Cases {
		fmt.Fprintf(b, "  %s = %d,
", c.Name, c.Value)
	}
	b.WriteString("}

")

	// Generate error class
	fmt.Fprintf(b, "export class %sError extends Error {
", enumName)
	fmt.Fprintf(b, "  constructor(public code: %s, message?: string) {
", enumName)
	b.WriteString("    super(message || `Contract error: ${code}`);
")
	b.WriteString("    this.name = '" + enumName + "Error';
")
	b.WriteString("  }
")
	b.WriteString("}

")
}

func (g *Generator) generateEventType(b *strings.Builder, ev xdr.ScSpecEventV0) {
	eventName := string(ev.Name)

	if ev.Doc != "" {
		fmt.Fprintf(b, "/** %s */
", ev.Doc)
	}

	fmt.Fprintf(b, "export interface %sEvent {
", eventName)
	for _, param := range ev.Params {
		tsType := g.mapTypeDefToTS(param.Type)
		location := "data"
		if param.Location == xdr.ScSpecEventParamLocationV0ScSpecEventParamLocationTopicList {
			location = "topic"
		}
		fmt.Fprintf(b, "  %s: %s; // %s
", param.Name, tsType, location)
	}
	b.WriteString("}

")
}

// mapTypeDefToTS converts Soroban type definitions to TypeScript types
func (g *Generator) mapTypeDefToTS(td xdr.ScSpecTypeDef) string {
	switch td.Type {
	case xdr.ScSpecTypeScSpecTypeVal:
		return "any"
	case xdr.ScSpecTypeScSpecTypeBool:
		return "boolean"
	case xdr.ScSpecTypeScSpecTypeVoid:
		return "void"
	case xdr.ScSpecTypeScSpecTypeError:
		return "Error"
	case xdr.ScSpecTypeScSpecTypeU32, xdr.ScSpecTypeScSpecTypeI32:
		return "number"
	case xdr.ScSpecTypeScSpecTypeU64, xdr.ScSpecTypeScSpecTypeI64:
		return "bigint"
	case xdr.ScSpecTypeScSpecTypeTimepoint:
		return "Date"
	case xdr.ScSpecTypeScSpecTypeDuration:
		return "number"
	case xdr.ScSpecTypeScSpecTypeU128, xdr.ScSpecTypeScSpecTypeI128:
		return "bigint"
	case xdr.ScSpecTypeScSpecTypeU256, xdr.ScSpecTypeScSpecTypeI256:
		return "bigint"
	case xdr.ScSpecTypeScSpecTypeBytes:
		return "Bytes"
	case xdr.ScSpecTypeScSpecTypeString:
		return "string"
	case xdr.ScSpecTypeScSpecTypeSymbol:
		return "Symbol"
	case xdr.ScSpecTypeScSpecTypeAddress:
		return "Address"
	case xdr.ScSpecTypeScSpecTypeMuxedAddress:
		return "Address"
	case xdr.ScSpecTypeScSpecTypeOption:
		if td.Option != nil {
			innerType := g.mapTypeDefToTS(td.Option.ValueType)
			return fmt.Sprintf("%s | null", innerType)
		}
		return "any | null"
	case xdr.ScSpecTypeScSpecTypeResult:
		if td.Result != nil {
			okType := g.mapTypeDefToTS(td.Result.OkType)
			errType := g.mapTypeDefToTS(td.Result.ErrorType)
			return fmt.Sprintf("Result<%s, %s>", okType, errType)
		}
		return "Result<any, any>"
	case xdr.ScSpecTypeScSpecTypeVec:
		if td.Vec != nil {
			elemType := g.mapTypeDefToTS(td.Vec.ElementType)
			return fmt.Sprintf("%s[]", elemType)
		}
		return "any[]"
	case xdr.ScSpecTypeScSpecTypeMap:
		if td.Map != nil {
			keyType := g.mapTypeDefToTS(td.Map.KeyType)
			valType := g.mapTypeDefToTS(td.Map.ValueType)
			return fmt.Sprintf("Map<%s, %s>", keyType, valType)
		}
		return "Map<any, any>"
	case xdr.ScSpecTypeScSpecTypeTuple:
		if td.Tuple != nil {
			types := make([]string, len(td.Tuple.ValueTypes))
			for i, t := range td.Tuple.ValueTypes {
				types[i] = g.mapTypeDefToTS(t)
			}
			return fmt.Sprintf("[%s]", strings.Join(types, ", "))
		}
		return "[]"
	case xdr.ScSpecTypeScSpecTypeBytesN:
		if td.BytesN != nil {
			return fmt.Sprintf("Uint8Array /* length: %d */", td.BytesN.N)
		}
		return "Uint8Array"
	case xdr.ScSpecTypeScSpecTypeUdt:
		if td.Udt != nil {
			return td.Udt.Name
		}
		return "any"
	default:
		return "any"
	}
}

// generateClient generates the main TypeScript client class
func (g *Generator) generateClient() string {
	var b strings.Builder

	b.WriteString("// Auto-generated TypeScript client for Soroban contract
")
	b.WriteString("// DO NOT EDIT - Generated by erst generate-bindings

")

	b.WriteString("import * as StellarSdk from '@stellar/stellar-sdk';
")
	b.WriteString("import { ErstSimulator } from './erst-integration';
")
	b.WriteString("import * as Types from './types';

")

	// Generate client configuration interface
	b.WriteString("export interface ClientConfig {
")
	b.WriteString("  contractId: string;
")
	b.WriteString("  network: 'testnet' | 'mainnet' | 'futurenet';
")
	b.WriteString("  rpcUrl?: string;
")
	b.WriteString("  enableSimulation?: boolean;
")
	b.WriteString("}

")

	// Generate method options interface
	b.WriteString("export interface CallOptions {
")
	b.WriteString("  simulate?: boolean;
")
	b.WriteString("  fee?: string;
")
	b.WriteString("  memo?: StellarSdk.Memo;
")
	b.WriteString("  timeoutInSeconds?: number;
")
	b.WriteString("}

")

	// Generate result type
	b.WriteString("export interface CallResult<T> {
")
	b.WriteString("  result: T;
")
	b.WriteString("  transactionHash?: string;
")
	b.WriteString("  simulation?: any;
")
	b.WriteString("}

")

	// Generate main client class
	className := toPascalCase(g.config.PackageName) + "Client"
	fmt.Fprintf(&b, "export class %s {
", className)
	b.WriteString("  private config: ClientConfig;
")
	b.WriteString("  private server: StellarSdk.SorobanRpc.Server;
")
	b.WriteString("  private simulator?: ErstSimulator;

")

	// Constructor
	b.WriteString("  constructor(config: ClientConfig) {
")
	b.WriteString("    this.config = config;
")
	b.WriteString("    
")
	b.WriteString("    // Initialize Soroban RPC server
")
	b.WriteString("    const networkUrl = config.rpcUrl || this.getDefaultRpcUrl(config.network);
")
	b.WriteString("    this.server = new StellarSdk.SorobanRpc.Server(networkUrl);
")
	b.WriteString("    
")
	b.WriteString("    // Initialize erst simulator if enabled
")
	b.WriteString("    if (config.enableSimulation) {
")
	b.WriteString("      this.simulator = new ErstSimulator({
")
	b.WriteString("        network: config.network,
")
	b.WriteString("        rpcUrl: networkUrl,
")
	b.WriteString("      });
")
	b.WriteString("    }
")
	b.WriteString("  }

")

	// Helper method for default RPC URL
	b.WriteString("  private getDefaultRpcUrl(network: string): string {
")
	b.WriteString("    switch (network) {
")
	b.WriteString("      case 'testnet':
")
	fmt.Fprintf(&b, "        return '%s';
", endpoints.SorobanTestnet)
	b.WriteString("      case 'mainnet':
")
	fmt.Fprintf(&b, "        return '%s';
", endpoints.SorobanMainnet)
	b.WriteString("      case 'futurenet':
")
	fmt.Fprintf(&b, "        return '%s';
", endpoints.SorobanFuturenet)
	b.WriteString("      default:
")
	b.WriteString("        throw new Error(`Unknown network: ${network}`);
")
	b.WriteString("    }
")
	b.WriteString("  }

")

	// Generate methods for each function
	if len(g.spec.Functions) > 0 {
		b.WriteString("  // Contract Methods

")
		for _, fn := range g.spec.Functions {
			g.generateClientMethod(&b, fn)
		}
	}

	// Add helper methods
	g.generateHelperMethods(&b)

	b.WriteString("}
")

	return b.String()
}

func (g *Generator) generateClientMethod(b *strings.Builder, fn xdr.ScSpecFunctionV0) {
	methodName := string(fn.Name)

	// Generate JSDoc comment
	if fn.Doc != "" {
		fmt.Fprintf(b, "  /** %s */
", fn.Doc)
	}

	// Generate method signature
	params := make([]string, 0, len(fn.Inputs)+2)
	params = append(params, "source: StellarSdk.Keypair")

	for _, inp := range fn.Inputs {
		tsType := g.mapTypeDefToTS(inp.Type)
		params = append(params, fmt.Sprintf("%s: %s", inp.Name, tsType))
	}

	params = append(params, "options?: CallOptions")

	returnType := "void"
	if len(fn.Outputs) > 0 {
		returnType = g.mapTypeDefToTS(fn.Outputs[0])
	}

	fmt.Fprintf(b, "  async %s(%s): Promise<CallResult<%s>> {
",
		methodName, strings.Join(params, ", "), returnType)

	// Method body
	b.WriteString("    const opts = options || {};

")

	// Build transaction
	b.WriteString("    // Build contract call transaction
")
	b.WriteString("    const contract = new StellarSdk.Contract(this.config.contractId);
")
	fmt.Fprintf(b, "    const operation = contract.call('%s'", methodName)

	if len(fn.Inputs) > 0 {
		for _, inp := range fn.Inputs {
			fmt.Fprintf(b, ", %s", inp.Name)
		}
	}

	b.WriteString(");

")

	b.WriteString("    const account = await this.server.getAccount(source.publicKey());
")
	b.WriteString("    const txBuilder = new StellarSdk.TransactionBuilder(account, {
")
	b.WriteString("      fee: opts.fee || StellarSdk.BASE_FEE,
")
	b.WriteString("      networkPassphrase: this.getNetworkPassphrase(),
")
	b.WriteString("    });

")

	b.WriteString("    if (opts.memo) {
")
	b.WriteString("      txBuilder.addMemo(opts.memo);
")
	b.WriteString("    }

")

	b.WriteString("    const tx = txBuilder
")
	b.WriteString("      .addOperation(operation)
")
	b.WriteString("      .setTimeout(opts.timeoutInSeconds || 30)
")
	b.WriteString("      .build();

")

	// Simulation with erst
	b.WriteString("    // Simulate with erst if enabled
")
	b.WriteString("    if (opts.simulate && this.simulator) {
")
	b.WriteString("      const simResult = await this.simulator.simulate(tx);
")
	b.WriteString("      return {
")
	b.WriteString("        result: simResult.result as " + returnType + ",
")
	b.WriteString("        simulation: simResult,
")
	b.WriteString("      };
")
	b.WriteString("    }

")

	// Execute transaction
	b.WriteString("    // Sign and submit transaction
")
	b.WriteString("    tx.sign(source);
")
	b.WriteString("    const response = await this.server.sendTransaction(tx);

")

	b.WriteString("    // Wait for confirmation
")
	b.WriteString("    if (response.status === 'PENDING') {
")
	b.WriteString("      const txResult = await this.server.getTransaction(response.hash);
")
	b.WriteString("      // Parse result and return
")
	b.WriteString("      return {
")
	b.WriteString("        result: this.parseResult(txResult) as " + returnType + ",
")
	b.WriteString("        transactionHash: response.hash,
")
	b.WriteString("      };
")
	b.WriteString("    }

")

	b.WriteString("    throw new Error(`Transaction failed: ${response.status}`);
")
	b.WriteString("  }

")
}

func (g *Generator) generateHelperMethods(b *strings.Builder) {
	b.WriteString("  // Helper Methods

")

	b.WriteString("  private getNetworkPassphrase(): string {
")
	b.WriteString("    switch (this.config.network) {
")
	b.WriteString("      case 'testnet':
")
	b.WriteString("        return StellarSdk.Networks.TESTNET;
")
	b.WriteString("      case 'mainnet':
")
	b.WriteString("        return StellarSdk.Networks.PUBLIC;
")
	b.WriteString("      case 'futurenet':
")
	b.WriteString("        return StellarSdk.Networks.FUTURENET;
")
	b.WriteString("      default:
")
	b.WriteString("        throw new Error(`Unknown network: ${this.config.network}`);
")
	b.WriteString("    }
")
	b.WriteString("  }

")

	b.WriteString("  private parseResult(txResult: any): any {
")
	b.WriteString("    // Parse transaction result from Soroban RPC response
")
	b.WriteString("    if (txResult.status === 'SUCCESS' && txResult.returnValue) {
")
	b.WriteString("      return StellarSdk.scValToNative(txResult.returnValue);
")
	b.WriteString("    }
")
	b.WriteString("    throw new Error('Transaction failed or no return value');
")
	b.WriteString("  }
")
}

// generateErstIntegration generates the erst simulator integration
func (g *Generator) generateErstIntegration() string {
	var b strings.Builder

	b.WriteString("// Erst simulator integration for local testing and debugging
")
	b.WriteString("// DO NOT EDIT - Generated by erst generate-bindings

")

	b.WriteString("import { spawn } from 'child_process';
")
	b.WriteString("import * as StellarSdk from '@stellar/stellar-sdk';

")

	b.WriteString("export interface ErstConfig {
")
	b.WriteString("  network: string;
")
	b.WriteString("  rpcUrl: string;
")
	b.WriteString("  erstPath?: string;
")
	b.WriteString("}

")

	b.WriteString("export interface SimulationResult {
")
	b.WriteString("  status: 'success' | 'error';
")
	b.WriteString("  result?: any;
")
	b.WriteString("  error?: string;
")
	b.WriteString("  events?: any[];
")
	b.WriteString("  logs?: string[];
")
	b.WriteString("  budgetUsage?: {
")
	b.WriteString("    cpuInstructions: number;
")
	b.WriteString("    memoryBytes: number;
")
	b.WriteString("    cpuUsagePercent: number;
")
	b.WriteString("    memoryUsagePercent: number;
")
	b.WriteString("  };
")
	b.WriteString("}

")

	b.WriteString("export class ErstSimulator {
")
	b.WriteString("  private config: ErstConfig;

")

	b.WriteString("  constructor(config: ErstConfig) {
")
	b.WriteString("    this.config = config;
")
	b.WriteString("  }

")

	b.WriteString("  async simulate(tx: StellarSdk.Transaction): Promise<SimulationResult> {
")
	b.WriteString("    const erstPath = this.config.erstPath || 'erst';
")
	b.WriteString("    
")
	b.WriteString("    // Convert transaction to XDR
")
	b.WriteString("    const envelopeXdr = tx.toEnvelope().toXDR('base64');
")
	b.WriteString("    
")
	b.WriteString("    return new Promise((resolve, reject) => {
")
	b.WriteString("      const args = [
")
	b.WriteString("        'simulate',
")
	b.WriteString("        '--network', this.config.network,
")
	b.WriteString("        '--rpc-url', this.config.rpcUrl,
")
	b.WriteString("        '--json',
")
	b.WriteString("      ];

")

	b.WriteString("      const erst = spawn(erstPath, args);
")
	b.WriteString("      let stdout = '';
")
	b.WriteString("      let stderr = '';

")

	b.WriteString("      erst.stdin.write(envelopeXdr);
")
	b.WriteString("      erst.stdin.end();

")

	b.WriteString("      erst.stdout.on('data', (data) => {
")
	b.WriteString("        stdout += data.toString();
")
	b.WriteString("      });

")

	b.WriteString("      erst.stderr.on('data', (data) => {
")
	b.WriteString("        stderr += data.toString();
")
	b.WriteString("      });

")

	b.WriteString("      erst.on('close', (code) => {
")
	b.WriteString("        if (code !== 0) {
")
	b.WriteString("          reject(new Error(`erst exited with code ${code}: ${stderr}`));
")
	b.WriteString("          return;
")
	b.WriteString("        }

")

	b.WriteString("        try {
")
	b.WriteString("          const result = JSON.parse(stdout);
")
	b.WriteString("          resolve(result);
")
	b.WriteString("        } catch (err) {
")
	b.WriteString("          reject(new Error(`Failed to parse erst output: ${err}`));
")
	b.WriteString("        }
")
	b.WriteString("      });
")
	b.WriteString("    });
")
	b.WriteString("  }

")

	b.WriteString("  async debugTransaction(txHash: string): Promise<SimulationResult> {
")
	b.WriteString("    const erstPath = this.config.erstPath || 'erst';
")
	b.WriteString("    
")
	b.WriteString("    return new Promise((resolve, reject) => {
")
	b.WriteString("      const args = [
")
	b.WriteString("        'debug',
")
	b.WriteString("        '--network', this.config.network,
")
	b.WriteString("        '--rpc-url', this.config.rpcUrl,
")
	b.WriteString("        '--json',
")
	b.WriteString("        txHash,
")
	b.WriteString("      ];

")

	b.WriteString("      const erst = spawn(erstPath, args);
")
	b.WriteString("      let stdout = '';
")
	b.WriteString("      let stderr = '';

")

	b.WriteString("      erst.stdout.on('data', (data) => {
")
	b.WriteString("        stdout += data.toString();
")
	b.WriteString("      });

")

	b.WriteString("      erst.stderr.on('data', (data) => {
")
	b.WriteString("        stderr += data.toString();
")
	b.WriteString("      });

")

	b.WriteString("      erst.on('close', (code) => {
")
	b.WriteString("        if (code !== 0) {
")
	b.WriteString("          reject(new Error(`erst exited with code ${code}: ${stderr}`));
")
	b.WriteString("          return;
")
	b.WriteString("        }

")

	b.WriteString("        try {
")
	b.WriteString("          const result = JSON.parse(stdout);
")
	b.WriteString("          resolve(result);
")
	b.WriteString("        } catch (err) {
")
	b.WriteString("          reject(new Error(`Failed to parse erst output: ${err}`));
")
	b.WriteString("        }
")
	b.WriteString("      });
")
	b.WriteString("    });
")
	b.WriteString("  }
")
	b.WriteString("}
")

	return b.String()
}

// generateIndex generates the main index.ts export file
func (g *Generator) generateIndex() string {
	var b strings.Builder

	b.WriteString("// Auto-generated index file
")
	b.WriteString("// DO NOT EDIT - Generated by erst generate-bindings

")

	b.WriteString("export * from './types';
")
	b.WriteString("export * from './client';
")
	b.WriteString("export * from './erst-integration';
")

	return b.String()
}

// generatePackageJSON generates package.json for the bindings
func (g *Generator) generatePackageJSON() string {
	return fmt.Sprintf(`{
  "name": "%s",
  "version": "1.0.0",
  "description": "TypeScript bindings for Soroban smart contract",
  "main": "index.js",
  "types": "index.d.ts",
  "scripts": {
    "build": "tsc",
    "test": "jest"
  },
  "dependencies": {
    "@stellar/stellar-sdk": "^12.0.0"
  },
  "devDependencies": {
    "@types/node": "^20.0.0",
    "typescript": "^5.0.0"
  },
  "keywords": [
    "stellar",
    "soroban",
    "smart-contract",
    "blockchain"
  ],
  "license": "Apache-2.0"
}
`, g.config.PackageName)
}

// generateReadme generates README.md documentation
func (g *Generator) generateReadme() string {
	var b strings.Builder

	className := toPascalCase(g.config.PackageName) + "Client"

	fmt.Fprintf(&b, "# %s

", g.config.PackageName)
	b.WriteString("TypeScript bindings for Soroban smart contract, generated by `erst generate-bindings`.

")

	b.WriteString("## Installation

")
	b.WriteString("```bash
")
	b.WriteString("npm install
")
	b.WriteString("```

")

	b.WriteString("## Usage

")
	b.WriteString("```typescript
")
	fmt.Fprintf(&b, "import { %s } from './%s';

", className, g.config.PackageName)

	b.WriteString("// Initialize client
")
	fmt.Fprintf(&b, "const client = new %s({
", className)
	if g.config.ContractID != "" {
		fmt.Fprintf(&b, "  contractId: '%s',
", g.config.ContractID)
	} else {
		b.WriteString("  contractId: 'YOUR_CONTRACT_ID',
")
	}
	fmt.Fprintf(&b, "  network: '%s',
", g.config.Network)
	b.WriteString("  enableSimulation: true, // Enable erst simulation
")
	b.WriteString("});

")

	b.WriteString("// Call contract methods
")
	if len(g.spec.Functions) > 0 {
		fn := g.spec.Functions[0]
		fmt.Fprintf(&b, "const result = await client.%s(
", string(fn.Name))
		b.WriteString("  sourceKeypair,
")
		for _, inp := range fn.Inputs {
			fmt.Fprintf(&b, "  %s, // %s
", inp.Name, g.mapTypeDefToTS(inp.Type))
		}
		b.WriteString("  { simulate: true } // Options
")
		b.WriteString(");

")
		b.WriteString("console.log('Result:', result);
")
	}
	b.WriteString("```

")

	b.WriteString("## Features

")
	b.WriteString("- **Type-safe**: Fully typed contract methods and data structures
")
	b.WriteString("- **Erst integration**: Built-in simulation and debugging with erst
")
	b.WriteString("- **Network support**: Works with testnet, mainnet, and futurenet
")
	b.WriteString("- **Error handling**: Strongly-typed error enums

")

	b.WriteString("## Contract Methods

")
	for _, fn := range g.spec.Functions {
		fmt.Fprintf(&b, "### `%s`

", string(fn.Name))
		if fn.Doc != "" {
			fmt.Fprintf(&b, "%s

", fn.Doc)
		}

		if len(fn.Inputs) > 0 {
			b.WriteString("**Parameters:**

")
			for _, inp := range fn.Inputs {
				fmt.Fprintf(&b, "- `%s`: `%s`
", inp.Name, g.mapTypeDefToTS(inp.Type))
			}
			b.WriteString("
")
		}

		if len(fn.Outputs) > 0 {
			fmt.Fprintf(&b, "**Returns:** `%s`

", g.mapTypeDefToTS(fn.Outputs[0]))
		}
	}

	b.WriteString("## Debugging with Erst

")
	b.WriteString("```typescript
")
	b.WriteString("// Simulate before executing
")
	b.WriteString("const simResult = await client.someMethod(
")
	b.WriteString("  sourceKeypair,
")
	b.WriteString("  args,
")
	b.WriteString("  { simulate: true }
")
	b.WriteString(");

")
	b.WriteString("// Check simulation results
")
	b.WriteString("console.log('Budget usage:', simResult.simulation.budgetUsage);
")
	b.WriteString("console.log('Events:', simResult.simulation.events);
")
	b.WriteString("```

")

	b.WriteString("## License

")
	b.WriteString("Apache-2.0
")

	return b.String()
}

// toPascalCase converts a string to PascalCase
func toPascalCase(s string) string {
	words := strings.FieldsFunc(s, func(r rune) bool {
		return r == '-' || r == '_' || r == ' '
	})

	for i, word := range words {
		if len(word) > 0 {
			words[i] = strings.ToUpper(word[:1]) + strings.ToLower(word[1:])
		}
	}

	return strings.Join(words, "")
}
